#!/usr/bin/perl -wT
$| = 1;
# reserveitemconfirm.cgi



use strict;
my $item;
my $key;
my @list;
my @wedfile;
my @temp;
my $time;
my $selecteditem;

print "Content-type; text/html\n\n";

print "<HTML><HEAD>\n<TITLE>";
print "Confirm Cancelled Item - Helen and Derek\'s wedding list.";
print "</TITLE>\n</HEAD>";

print "<BODY bgcolor=mistyrose>\n";

if ($ENV{'HTTP_REFERER'} !~ m#^http://www.todd.uklinux.net/#) {
    print "You may only enter this site via the homepage.\n </BODY></HTML>\n";
    exit;
}

print "<H2>Please confirm your selection;</H2>";

# Get the ID of the item selected
@temp=split(/==/,$ENV{QUERY_STRING});
$selecteditem=$temp[1];

# Get the table details from a csv file and output as a perl data structure

# First, read the csv file into an array...
open (TEMP, "<wedtablelist.cgi");
@wedfile = <TEMP>;
close (TEMP);

print "<TABLE align=center border=2 bgcolor=\"ffffcc\" cellpadding=2 width=95\%>";

# Now, locate and dispay the selected item
foreach $item (@wedfile) {
    my @list=split(/,/, $item);
    $key=shift(@list);
    if ($key eq $selecteditem) {
        print "<TR><TD><B>$key</B>";
        foreach my $i (@list) {
            print "<TD>$i";
            print "&nbsp" unless ($i);
        }
        print "</TR>\n";
    }

print "</TABLE>\n";

print "<P>&nbsp;</P>\n";

$time = scalar time();

print <<"End of block";
<P>&nbsp;</P>\n
<FORM action=\"reserveitem.cgi?item=$selecteditem=$time\" METHOD=POST>\n
<P>Please add any short comments here (e.g. reserved on behalf of...</P>\n
<P>Letters andf numbers only, please!)</P>\n
<INPUT TYPE=\"TEXT\" name=\"comments2 size=65 maxlength=62>\n
<P></P>\n
<INPUT type=\"submit\" value=\"Reserve\">\n
</FORM>\n
<P>&nbsp;</P>\n
End of block

print "<BR size=6 width=90\%>\n"; 
print "<P align=center><STRONG>If you do not wish to reserve this item after all, click <A href=\"wedtable.cgi?item=$selecteditem\">here</A></STRONG></P>\n";

print "</BODY></HTML>\n";